#!/usr/bin/env bash
# Regenerate each retained legacy EventLog fixture set at the commit its README
# claims, using the pinned generator, and require identical file sets and bytes.
# LEGACY_FIXTURE_DIR selects a separate retained copy for negative controls.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"
fixtures="rust/crates/safemesh-crdt/tests/fixtures/legacy-event-log"
retained_root="${LEGACY_FIXTURE_DIR:-$fixtures}"
scratch_root="${RUNNER_TEMP:-${TMPDIR:-$PWD}}"
scratch="$(mktemp -d "$scratch_root/safemesh-legacy-log.XXXXXX")"

check() {
  local frame="$1" subdir="$2"
  local sha
  sha="$(sed -n "s/^${frame} source: \`\([0-9a-f]\{40\}\)\`\.\$/\1/p" "$fixtures/README.md")"
  if [ -z "$sha" ]; then
    echo "$fixtures/README.md: no claimed source line for $frame" >&2
    exit 1
  fi
  if ! git merge-base --is-ancestor "$sha" HEAD; then
    echo "$frame source $sha is not an ancestor of HEAD" >&2
    exit 1
  fi
  local work="$scratch/$subdir"
  mkdir -p "$work/baseline"
  git archive "$sha" | tar -x -C "$work/baseline"
  cp "$fixtures/generate.rs" "$work/baseline/rust/crates/safemesh-crdt/tests/legacy_generate.rs"
  TMPDIR="$scratch" LEGACY_EVENT_LOG_GENERATE="$work/generated" cargo test \
    --manifest-path "$work/baseline/rust/Cargo.toml" -p safemesh-crdt \
    --test legacy_generate generate_legacy_event_logs -- --ignored --exact --nocapture
  local retained="$retained_root/$subdir"
  find "$work/generated" -type f -printf '%P\n' | LC_ALL=C sort > "$work/generated-files"
  find "$retained" -type f -printf '%P\n' | LC_ALL=C sort > "$work/retained-files"
  if ! diff -u "$work/generated-files" "$work/retained-files"; then
    echo "$retained: file set differs from $frame regeneration at $sha" >&2
    exit 1
  fi
  while IFS= read -r name; do
    if ! cmp "$work/generated/$name" "$retained/$name"; then
      echo "$retained/$name: bytes differ from $frame regeneration at $sha" >&2
      exit 1
    fi
  done < "$work/generated-files"
  echo "$frame: $(wc -l < "$work/generated-files") files regenerated byte-identical at $sha"
}

check "Tag 0x02" tag02
check "Unshaped tag 0x03" tag03-unshaped
