// SafeMesh — delta-state CRDT convergence, built on crdt-lean.
// Copyright (C) 2026 Ben Cassie
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Differential conformance against the Lean-emitted oracle corpus.
//!
//! `tests/corpus.json` is GENERATED by the machine-checked Lean definitions
//! (`cd lean && lake exe corpus > ../rust/crates/safemesh-crdt/tests/corpus.json`)
//! — every expected output below was computed by the proven model, not
//! hand-written. Each case's bump sequence is replayed through the Rust
//! implementation in delivery order and the final state + value must match
//! the oracle exactly. The corpus includes permutations and redeliveries of
//! identical bump-sets, so the proven order/duplicate-insensitivity
//! (`SafeMesh.delta_dissemination_sec`) is exercised, not assumed.
//!
//! The library is `no_std`; this harness is std + serde_json (dev-dependency
//! only) — that split is deliberate.

use safemesh_crdt::{GCounter, PnCounter};
use serde_json::Value;

const CORPUS: &str = include_str!("corpus.json");

fn as_usize(v: &Value) -> usize {
    v.as_u64().expect("expected unsigned integer") as usize
}

#[test]
fn corpus_is_the_expected_schema() {
    let corpus: Value = serde_json::from_str(CORPUS).expect("corpus.json parses");
    assert_eq!(corpus["schema"], "safemesh-conformance-v1");
    assert!(corpus["gcounter"].as_array().unwrap().len() >= 9);
    assert!(corpus["pncounter"].as_array().unwrap().len() >= 9);
}

#[test]
fn gcounter_matches_lean_oracle() {
    let corpus: Value = serde_json::from_str(CORPUS).expect("corpus.json parses");
    for case in corpus["gcounter"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let n = as_usize(&case["n"]);
        let mut g = GCounter::new(n);
        for bump in case["bumps"].as_array().unwrap() {
            let b = bump.as_array().unwrap();
            g.apply_bump(as_usize(&b[0]), b[1].as_u64().unwrap());
        }
        let expected_state: Vec<u64> = case["expected_state"]
            .as_array().unwrap().iter().map(|v| v.as_u64().unwrap()).collect();
        assert_eq!(g.state(), expected_state.as_slice(), "state mismatch in {name}");
        assert_eq!(g.value(), case["expected_value"].as_u64().unwrap(), "value mismatch in {name}");
    }
}

#[test]
fn pncounter_matches_lean_oracle() {
    let corpus: Value = serde_json::from_str(CORPUS).expect("corpus.json parses");
    for case in corpus["pncounter"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let n = as_usize(&case["n"]);
        let mut pn = PnCounter::new(n);
        for op in case["ops"].as_array().unwrap() {
            let o = op.as_array().unwrap();
            let (kind, replica, tally) = (o[0].as_str().unwrap(), as_usize(&o[1]), o[2].as_u64().unwrap());
            match kind {
                "inc" => pn.apply_inc(replica, tally),
                "dec" => pn.apply_dec(replica, tally),
                other => panic!("unknown op kind {other:?} in {name}"),
            }
        }
        let expected_p: Vec<u64> = case["expected_p"]
            .as_array().unwrap().iter().map(|v| v.as_u64().unwrap()).collect();
        let expected_n: Vec<u64> = case["expected_n"]
            .as_array().unwrap().iter().map(|v| v.as_u64().unwrap()).collect();
        assert_eq!(pn.p_state(), expected_p.as_slice(), "P mismatch in {name}");
        assert_eq!(pn.n_state(), expected_n.as_slice(), "N mismatch in {name}");
        assert_eq!(pn.value(), case["expected_value"].as_i64().unwrap(), "value mismatch in {name}");
    }
}

/// The convergence shape itself, cross-checked in Rust: merging two replicas
/// that each saw HALF the corpus bumps equals the replica that saw them all —
/// the gossip step `SafeMesh.merge_deltaState`, exercised over oracle data.
#[test]
fn split_delivery_merge_agrees_with_oracle() {
    let corpus: Value = serde_json::from_str(CORPUS).expect("corpus.json parses");
    for case in corpus["gcounter"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let n = as_usize(&case["n"]);
        let bumps = case["bumps"].as_array().unwrap();
        let (mut left, mut right) = (GCounter::new(n), GCounter::new(n));
        for (idx, bump) in bumps.iter().enumerate() {
            let b = bump.as_array().unwrap();
            let target = if idx % 2 == 0 { &mut left } else { &mut right };
            target.apply_bump(as_usize(&b[0]), b[1].as_u64().unwrap());
        }
        left.merge(&right);
        let expected_state: Vec<u64> = case["expected_state"]
            .as_array().unwrap().iter().map(|v| v.as_u64().unwrap()).collect();
        assert_eq!(left.state(), expected_state.as_slice(), "split-merge mismatch in {name}");
    }
}
